### ISSUE TITLE
@import is not working

### ISSUE THREAD

**Issue by turboMaCk** [meoblast001/hakyll-sass#7]
Hello!
Sass `@import` is not working for me.

Actual error is:

```
libc++abi.dylib: terminating with uncaught exception of type Sass::Exception::InvalidSyntax: File to import not found or unreadable: s
Parent style sheet: stdin
```

I'm using hakyll 4.9 on OSX with cabal. Anyway I've got same error while using version compiled by hand using just ghc. Also I have this warning: https://github.com/meoblast001/hakyll-sass/issues/3 (Which I can help debug if you want).

Cheers!
Marek

**Comment by meoblast001** [comment]
Hello. I noticed the problem seems to be in the way I load the file and pass it to libsass. To verify whether my solution works for you, could you do the following? Check out project and switch to branch "develop". From your project, do `cabal sandbox add-source $PATH_TO_HAKYLL_SASS`, where `$PATH_TO_HAKYLL_SASS` is the path to your hakyll-sass directory. Rerun the build and let me know what happens.

**Comment by turboMaCk** [comment]
Works like a charm! 🚀 

Great job! Thank you very much!

![screen_shot_2016-11-02_at_23_48_56](https://cloud.githubusercontent.com/assets/2130305/19950352/349d2b04-a157-11e6-8c52-24ca6fcf253a.png)

**Comment by meoblast001** [comment]
This sounds good. I'll try to include this in a bug fix release in the next few days.
